import './globals.css'
import { Inter } from 'next/font/google'
import { Suspense } from "react";
import Loading from './loading';
import NavBar from './Components/NavBar/NavBar';
import Footer from './Components/Footer/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
    <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
